# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

################################################################################
#
#    Arma Consenter Configuration Template
#
################################################################################

# PartyID a unique identifier for each Arma party, uint16, id>0
PartyID: 1

################################################################################
#
#   SECTION: General: same as in template
#
################################################################################
General:

################################################################################
#
#   SECTION: File Store: same as in template
#
################################################################################
FileStore:
  Location: /var/dec-trust/production/orderer

################################################################################
#
#   SECTION: Role specific configuration: only `Consensus` key
#
################################################################################

# Consensus specific parameters
Consensus:
  # WALDir specifies the location at which Write Ahead Logs for SmartBFT are
  # stored. If not set, it defaults to <FileStore.Location>/wal.
  WALDir:
